force-app/main/default/objects/JobSearchCriteria__c/JobSearchCriteria__c.object-meta.xml
<CustomObject>
    <description>Used to start and track the current searches.</description>
    <label>Job Search Criteria</label>
    <nameField>
        <displayFormat>JS-{0}</displayFormat>
        <label>Job Search Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Search Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobSearchCriteria__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Indicates which city you want to search in.</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobSearchCriteria__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates this search is active.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JobSearchCriteria__c/fields/JobTitle__c.field-meta.xml
<CustomField>
    <fullName>JobTitle__c</fullName>
    <description>Indicates which job title you are searching for.</description>
    <label>Job Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobSearchCriteria__c/fields/LabelTrig__c.field-meta.xml
<CustomField>
    <fullName>LabelTrig__c</fullName>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/JobSearchCriteria__c/fields/StatePick__c.field-meta.xml
<CustomField>
    <fullName>StatePick__c</fullName>
    <description>Indicates which state you want to search.</description>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobSearchTriggerHandler.cls
public with sharing class JobSearchTriggerHandler {
    public static void scheduleNewJobSearch(List<JobSearchCriteria__c> triggerDotNew) {
        //Search for crontrigger where CronJobDetail.Name = JobTitle + Location if one exist do nothing if one doesnt create it.
        Map<String, JobSearchCriteria__c> cronTitleToTriggerMap = new Map<String,JobSearchCriteria__c>();
        for(JobSearchCriteria__c search: triggerDotNew){
            if(search.IsActive__c){
                cronTitleToTriggerMap.put(searchTitle(search.JobTitle__c, search.City__c, search.StatePick__c), search);
            }
        }
        Map<String, CronTrigger> existingCronTriggerMap = new Map<String, CronTrigger>();
        for(CronTrigger crTrig : [SELECT Id,CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name IN:cronTitleToTriggerMap.keySet()]){
            existingCronTriggerMap.put(crTrig.CronJobDetail.Name, crTrig);
        }
        for(JobSearchCriteria__c search: triggerDotNew){
            String searchLabel = searchTitle(search.JobTitle__c, search.City__c, search.StatePick__c);
            if(existingCronTriggerMap.get(searchLabel) == null && search.IsActive__c){
                JoobleIntegration_Schedule scheduleJob = new JoobleIntegration_Schedule(search.JobTitle__c, search.City__c + ', ' + search.StatePick__c);
                String cron = '0 0 0 ? * *';//Every day at midnight
                System.schedule(searchLabel, cron, scheduleJob);
            }
        }

    }
    public static void updateJobSearch(List<JobSearchCriteria__c> triggerDotNew, Map<Id, JobSearchCriteria__c> triggerDotOldMap) {
        Map<String, JobSearchCriteria__c> cronTitleToTriggerMap = new Map<String,JobSearchCriteria__c>();
        Set<String> labelsToAbort = new Set<String>();
        for(JobSearchCriteria__c search: triggerDotNew){
            JobSearchCriteria__c oldSearch = triggerDotOldMap.get(search.Id);
            if((search.LabelTrig__c != oldSearch.LabelTrig__c) || (search.IsActive__c == false && oldSearch.IsActive__c)){
                labelsToAbort.add(oldSearch.LabelTrig__c);
            }
        }
        for(CronTrigger crTrig : [SELECT Id,CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name IN:labelsToAbort]){
            System.abortJob(crTrig.Id);
        }
        scheduleNewJobSearch(triggerDotNew);
    }
    public static void clearJobSearch(List<JobSearchCriteria__c> triggerDotOld){
        Set<String> searchesToDelete = new Set<String>();
        for(JobSearchCriteria__c search: triggerDotOld){
            searchesToDelete.add(searchTitle(search.JobTitle__c, search.City__c, search.StatePick__c));
        }
        for(CronTrigger crTrig : [SELECT Id,CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name IN:searchesToDelete]){
            System.abortJob(crTrig.Id);
        }
    }
    public static void preventDuplication(List<JobSearchCriteria__c> triggerDotNew){
        for(JobSearchCriteria__c search: triggerDotNew){
            search.LabelTrig__c = searchTitle(search.JobTitle__c, search.City__c, search.StatePick__c);
        }

    }
    private static String searchTitle(String title, String city, String state){
        return title + ' ' + city + ', ' + state;
    }
}