force-app/main/default/objects/JobSearchCriteria__c/JobSearchCriteria__c.object-meta.xml
<CustomObject>
    <description>Used to start and track the current searches.</description>
    <label>Job Search Criteria</label>
    <nameField>
        <displayFormat>JS-{0}</displayFormat>
        <label>Job Search Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Search Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobSearchCriteria__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Indicates which city you want to search in.</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobSearchCriteria__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates this search is active.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JobSearchCriteria__c/fields/JobTitle__c.field-meta.xml
<CustomField>
    <fullName>JobTitle__c</fullName>
    <description>Indicates which job title you are searching for.</description>
    <label>Job Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobSearchCriteria__c/fields/StatePick__c.field-meta.xml
<CustomField>
    <fullName>StatePick__c</fullName>
    <description>Indicates which state you want to search.</description>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>Texas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobSearchTriggerHandler_Test.cls
@isTest
public with sharing class JobSearchTriggerHandler_Test {
    @isTest
    static void confirmDefaultSearchCreated() {
        CronTrigger defaultJob = [SELECT CronJobDetail.Name, NextFireTime, Id FROM CronTrigger WHERE CronJobDetail.Name = 'Digital Overlord Accident, Maryland' LIMIT 1];
        Assert.areEqual('Digital Overlord Accident, Maryland', defaultJob.CronJobDetail.Name);
    }
    @isTest
    static void setDefaultSearchToInactive(){
        Test.startTest();
        JobSearchCriteria__c defaultSearch = [SELECT Id, IsActive__c FROM JobSearchCriteria__c WHERE JobTitle__c = 'Digital Overlord'];
        defaultSearch.IsActive__c = false;
        update defaultSearch;
        Test.stopTest();
        List<CronTrigger> cronList = [SELECT CronJobDetail.Name, NextFireTime, Id FROM CronTrigger WHERE CronJobDetail.Name = 'Digital Overlord Accident, Maryland'];
        Assert.areEqual(0, cronList.size());
    }
    @isTest
    static void deleteDefaultSearch(){
        Test.startTest();
        JobSearchCriteria__c defaultSearch = [SELECT Id, IsActive__c FROM JobSearchCriteria__c WHERE JobTitle__c = 'Digital Overlord'];
        defaultSearch.IsActive__c = false;
        delete defaultSearch;
        Test.stopTest();
        List<CronTrigger> cronList = [SELECT CronJobDetail.Name, NextFireTime, Id FROM CronTrigger WHERE CronJobDetail.Name = 'Digital Overlord Accident, Maryland'];
        Assert.areEqual(0, cronList.size());
    }
    @isTest
    static void testForcedLimit(){
        List<JobSearchCriteria__c> jobSearchList = new List<JobSearchCriteria__c>();
        for(Integer i = 0 ; i < 51; i++ ){
            JobSearchCriteria__c bulkSearchInsert = new JobSearchCriteria__c(
            IsActive__c = true,
            StatePick__c = 'Texas',
            City__c = 'Ding Dong',
            JobTitle__c = 'Ditcher ' + i
            );
            jobSearchList.add(bulkSearchInsert);
        }
        try {
            insert jobSearchList;
            Assert.fail('Expected failure over 50 at once.');
        } catch(Exception e) {
            Assert.isTrue(e.getMessage().contains('Object Limit Exceeded: Only 50 Search Criteria may be modified at a time.'), 'Expected failure over 50 at once.');
        }
    }
    @isTest
    static void testInsertingDuplicate(){
        JobSearchCriteria__c defaultSearch = new JobSearchCriteria__c(
            IsActive__c = true,
            StatePick__c = 'Maryland',
            City__c = 'Accident',
            JobTitle__c = 'Digital Overlord'
        );
        try {
            insert defaultSearch;
            Assert.fail('Expected failure duplicate value found.');
        } catch (Exception e) {
            Assert.isTrue(e.getMessage().contains('DUPLICATE_VALUE, duplicate value found:'), 'Expected failure duplicate value found.');
        }
    }
    @TestSetup
    static void makeData(){
        JobSearchCriteria__c defaultSearch = new JobSearchCriteria__c(
            IsActive__c = true,
            StatePick__c = 'Maryland',
            City__c = 'Accident',
            JobTitle__c = 'Digital Overlord'
        );
        insert defaultSearch;
    }
}