force-app/main/default/objects/Contact_Association__c/Contact_Association__c.object-meta.xml
<CustomObject>
    <description>Relationship between contacts and job applications</description>
    <label>Contact Association</label>
    <nameField>
        <label>Contact Association</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContactAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Contact related to the Job Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>ContactAssociations</relationshipLabel>
    <relationshipName>ContactAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Association__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <description>Job application the contact is related to.</description>
    <label>Job Application</label>
    <referenceTo>JobApplication__c</referenceTo>
    <relationshipLabel>ContactAssociations</relationshipLabel>
    <relationshipName>JobApplications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactAssociation__c/ContactAssociation__c.object-meta.xml
<CustomObject>
    <description>Relationship between contacts and job applications</description>
    <label>Contact Association</label>
    <nameField>
        <label>Contact Association</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactAssociation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Contact related to the Job Application</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>ContactAssociations</relationshipLabel>
    <relationshipName>ContactAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactAssociation__c/fields/JobApplication__c.field-meta.xml
<CustomField>
    <fullName>JobApplication__c</fullName>
    <description>Job application the contact is related to.</description>
    <label>Job Application</label>
    <referenceTo>JobApplication__c</referenceTo>
    <relationshipLabel>ContactAssociations</relationshipLabel>
    <relationshipName>JobApplications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <description>Used to track an application to a Job Posting.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplication__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Main point of contact for the job application</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/JobApplicationHelper.cls
public with sharing class JobApplicationHelper {
    public static void setPrimaryContact(Map<Id,JobApplication__c> newJobApplicationMap) {
        for (JobApplication__c jobApp : newJobApplicationMap.values()){
            // if contact is added, see if there is a matching primary contact
            if (jobApp.Contact__c != null){
                continue;
            } else if (areRelatedContactsAvailable(jobApp)){
                jobApp.Contact__c = jobApp.JobApplications__r[0].Contact__c;
            }
        }
    }

    private static Boolean areRelatedContactsAvailable(JobApplication__c jobApp){
        return jobApp.JobApplications__r != null && jobApp.JobApplications__r.size()>0;
    }
    
}