force-app/main/default/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <description>Used to track an application to a Job Posting.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Company associated with the application target</description>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Main point of contact for the job application</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/JobPostingRef__c.field-meta.xml
<CustomField>
    <fullName>JobPostingRef__c</fullName>
    <description>The job posting that we applying to.</description>
    <label>Job Posting</label>
    <referenceTo>JobPosting__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>JobApplications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Needed for Path</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/JobPosting__c/JobPosting__c.object-meta.xml
<CustomObject>
    <description>Used to hold a posting of a role from a account.</description>
    <label>Job Posting</label>
    <nameField>
        <label>Job Posting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JobPosting__c/fields/CompanyRef__c.field-meta.xml
<CustomField>
    <fullName>CompanyRef__c</fullName>
    <description>The account that has posted this job.</description>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Postings</relationshipLabel>
    <relationshipName>JobPostings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JobApplicationHelperTest.cls
@isTest
private class JobApplicationHelperTest {
    @isTest 
    static void setPrimaryContactTest() {
        Account acc = new Account(Name = 'Account Test 1');
        insert acc;
        JobPosting__c newJobPosting = new JobPosting__c();
        newJobPosting.CompanyRef__c = acc.Id;
        insert newJobPosting;
        JobApplication__c newJobApplication = new JobApplication__c();
        newJobApplication.Name = 'Test Application';
        newJobApplication.Account__c = acc.Id;
        newJobApplication.JobPostingRef__c = newJobPosting.Id;
        insert newJobApplication;

        Test.startTest();
        JobApplicationHelper.setPrimaryContact(new Map<Id, JobApplication__c>{ 
            newJobApplication.id => newJobApplication
        });
        Test.stopTest();
        JobApplication__c results = [SELECT Id, Contact__c FROM JobApplication__c LIMIT 1];
        Assert.isNotNull(results.Contact__c, 'Expected a primary contact to be updated');
    }
}