force-app/main/default/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <description>Used to track an application to a Job Posting.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Company associated with the application target</description>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/JobPostingRef__c.field-meta.xml
<CustomField>
    <fullName>JobPostingRef__c</fullName>
    <description>The job posting that we applying to.</description>
    <label>Job Posting</label>
    <referenceTo>JobPosting__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>JobApplications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JobPosting__c/JobPosting__c.object-meta.xml
<CustomObject>
    <description>Used to hold a posting of a role from a account.</description>
    <label>Job Posting</label>
    <nameField>
        <label>Job Posting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JobPosting__c/fields/CompanyRef__c.field-meta.xml
<CustomField>
    <fullName>CompanyRef__c</fullName>
    <description>The account that has posted this job.</description>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Postings</relationshipLabel>
    <relationshipName>JobPostings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventTriggerHandler_Test.cls
@isTest
public with sharing class EventTriggerHandler_Test {
    @isTest
    static void testNoOverlapButOtherEvents() {
        Event newEvent = new Event(
            StartDateTime = Datetime.newInstance(2124,6,19,13,15,2),
            EndDateTime = Datetime.newInstance(2124,6,19,13,45,2)
        );
        insert newEvent;
        Assert.areEqual(2, [SELECT Id FROM Event].size(), 'Expected two events created.');
    }
    @isTest
    static void testOverlapWithOtherEvents() {
        Event newEvent = new Event(
            StartDateTime = Datetime.newInstance(2124,6,19,12,45,2),
            EndDateTime = Datetime.newInstance(2124,6,19,13,30,2)
        );
        try {
            insert newEvent;
        } catch (Exception ex) {
            Boolean expectedExceptionThrown = ex.getMessage().contains('You have another scheduled event at this time.');
            Assert.areEqual(true, expectedExceptionThrown, 'Expected failure due to overlapping custom exception.');
        }
    }
    @isTest
    static void testOnAWeekend() {
        Event newEvent = new Event(
            StartDateTime = Datetime.newInstance(2124,6,25,12,45,2),
            EndDateTime = Datetime.newInstance(2124,6,25,13,30,2)
        );
        try {
            insert newEvent;
        } catch (Exception ex) {
            Boolean expectedExceptionThrown = ex.getMessage().contains('This is your off day, stop working. Unlike the people who made this.');
            Assert.areEqual(true, expectedExceptionThrown, 'Expected failure due to weekend custom exception.');
        }
    }
    @TestSetup
    static void makeData() {
        Account acc = new Account(
            Name = 'Mars'
        );
        insert acc;
        JobPosting__c jobPost = new JobPosting__c(
            CompanyRef__c = acc.Id,
            Name = 'Repair Technician'
        );
        insert jobPost;
        JobApplication__c jobApp = new JobApplication__c(
            Account__c = acc.Id,
            Name = 'I\'m thinking this should be an Autonumber now...',
            JobPostingRef__c = jobPost.Id
        );
        insert jobApp;
        Event newEvent = new Event(
            StartDateTime = Datetime.newInstance(2124,6,19,12,30,2),
            EndDateTime = Datetime.newInstance(2124,6,19,13,00,2)
        );
        insert newEvent;
    }
}