force-app/main/default/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <description>Used to track an application to a Job Posting.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplication__c/fields/Follow_up_date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_date__c</fullName>
    <description>Date for next scheduled communication</description>
    <label>Follow-up date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Application status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateStaleJobApplication_Batch.cls
public class UpdateStaleJobApplication_Batch implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id, Status__c, CreatedById ';
        query += 'FROM JobApplication__c ';
        query += 'WHERE Status__c != \'Closed\' ';
        query += 'AND Follow_up_date__c > LAST_N_DAYS:30';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<JobApplication__c> scope) {
        List<Task> tasksToCreate = new List<Task>();
        for(JobApplication__c jobApp : scope){
            jobApp.Status__c = 'Closed';
            Task newTask = new Task(
                WhatId = jobApp.Id,
                Subject = 'Closed By Automated Process',
                Status = 'Completed',
                OwnerId = jobApp.CreatedById
            );
            tasksToCreate.add(newTask);
        }
        update as system scope;
        insert as system tasksToCreate;
    }

    public void finish(Database.BatchableContext bc){
        System.debug('Executing secret function...');
        System.debug('Muahahahahahahahahaha!!');
        System.debug('You have no idea what you have started!');
    }
}