force-app/main/default/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <description>Used to track an application to a Job Posting.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplication__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Company associated with the application target</description>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/Follow_up_date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_date__c</fullName>
    <description>Date for next scheduled communication</description>
    <label>Follow-up date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/JobPostingRef__c.field-meta.xml
<CustomField>
    <fullName>JobPostingRef__c</fullName>
    <description>The job posting that we applying to.</description>
    <label>Job Posting</label>
    <referenceTo>JobPosting__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>JobApplications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Application status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobPosting__c/JobPosting__c.object-meta.xml
<CustomObject>
    <description>Used to hold a posting of a role from a account.</description>
    <label>Job Posting</label>
    <nameField>
        <label>Job Posting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JobPosting__c/fields/CompanyRef__c.field-meta.xml
<CustomField>
    <fullName>CompanyRef__c</fullName>
    <description>The account that has posted this job.</description>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Postings</relationshipLabel>
    <relationshipName>JobPostings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UpdateStaleJobApplication_Test.cls
@isTest
public with sharing class UpdateStaleJobApplication_Test {
    @isTest
    static void testBatchingUpdate(){
        Test.startTest();
        UpdateStaleJobApplication_Batch batch = new UpdateStaleJobApplication_Batch();
        Id batchId = Database.executeBatch(batch);
        Test.stopTest();

        List<JobApplication__c> updatedJobApp = [SELECT Id, Status__c FROM JobApplication__c WHERE Follow_Up_Date__c < LAST_N_DAYS:30];
        List<Task> createdTask = [SELECT Id, Subject FROM Task WHERE Subject = 'Closed By Automated Process'];

        for(JobApplication__c jobApp : updatedJobApp){
            Assert.areEqual('Closed', jobApp.Status__c, 'Expected status updated to Closed');
        }
        Assert.areEqual(updatedJobApp.size(), createdTask.size(), 'Expected equal amount of created task to automatically closed JobApps');
    }
    @isTest
    static void testSchedule(){
        Test.startTest();
        UpdateStaleJobApplication_Schedule scheduleJob = new UpdateStaleJobApplication_Schedule();
        String year = String.valueOf(Date.today().year() + 1);
        String cron = '0 0 0 15 3 ? ' + year;
        System.schedule('Test Schedule', cron, scheduleJob);
        scheduleJob.execute(null);
        Test.stopTest();

        List<JobApplication__c> updatedJobApp = [SELECT Id, Status__c FROM JobApplication__c WHERE Follow_Up_Date__c < LAST_N_DAYS:30];
        List<Task> createdTask = [SELECT Id, Subject FROM Task WHERE Subject = 'Closed By Automated Process'];

        for(JobApplication__c jobApp : updatedJobApp){
            Assert.areEqual('Closed', jobApp.Status__c, 'Expected status updated to Closed');
        }
        Assert.areEqual(updatedJobApp.size(), createdTask.size(), 'Expected equal amount of created task to automatically closed JobApps');
    }
    @TestSetup
    static void makeData(){
        Account acc = new Account(
            Name = 'Mars'
        );
        insert acc;
        JobPosting__c jobPost = new JobPosting__c(
            CompanyRef__c = acc.Id,
            Name = 'Repair Technician'
        );
        insert jobPost;
        Date todayMinus45 = Date.today() - 45;
        JobApplication__c jobApp = new JobApplication__c(
            Account__c = acc.Id,
            Name = 'I\'m thinking this should be an Autonumber now...',
            JobPostingRef__c = jobPost.Id,
            Follow_Up_Date__c = todayMinus45
        );
        insert jobApp;
    }
}